# @package _global_

# 训练配置
training:
  batch_size: 4
  epochs: 100
  num_workers: 4
  save_every: 10
  eval_every: 5
  
  # 优化器配置
  optimizer:
    type: "adamw"
    lr: 1e-4
    weight_decay: 1e-5
    betas: [0.9, 0.999]
    eps: 1e-8
    
  # 学习率调度器配置
  scheduler:
    type: "cosine"
    T_max: 100
    eta_min: 1e-7
    warmup_epochs: 10
    warmup_factor: 0.1
    
  # 梯度裁剪
  gradient_clip:
    enabled: true
    max_norm: 1.0
    norm_type: 2
    
  # 混合精度训练
  amp:
    enabled: true
    loss_scale: "dynamic"
    
  # 早停机制
  early_stopping:
    enabled: true
    patience: 15
    min_delta: 1e-6
    
  # 检查点配置
  checkpoint:
    save_best: true
    save_last: true
    save_top_k: 3
    monitor: "val_iou"
    mode: "max" 